(ns early-vote-site.constants)

(def states
  [{:fips-code "01" :state-name "Alabama"},
   {:fips-code "02" :state-name "Alaska"}
   {:fips-code "04" :state-name "Arizona"}
   {:fips-code "05" :state-name "Arkansas"},
   {:fips-code "06" :state-name "California"},
   {:fips-code "08" :state-name "Colorado"},
   {:fips-code "09" :state-name "Connecticut"},
   {:fips-code "10" :state-name "Delaware"},
   {:fips-code "11" :state-name "District of Columbia"},
   {:fips-code "12" :state-name "Florida"},
   {:fips-code "13" :state-name "Georgia"},
   {:fips-code "15" :state-name "Hawaii"},
   {:fips-code "16" :state-name "Idaho"},
   {:fips-code "17" :state-name "Illinois"},
   {:fips-code "18" :state-name "Indiana"},
   {:fips-code "19" :state-name "Iowa"},
   {:fips-code "20" :state-name "Kansas"},
   {:fips-code "21" :state-name "Kentucky"},
   {:fips-code "22" :state-name "Louisiana"},
   {:fips-code "23" :state-name "Maine"},
   {:fips-code "24" :state-name "Maryland"},
   {:fips-code "25" :state-name "Massachusetts"},
   {:fips-code "26" :state-name "Michigan"},
   {:fips-code "27" :state-name "Minnesota"},
   {:fips-code "28" :state-name "Mississippi"},
   {:fips-code "29" :state-name "Missouri"},
   {:fips-code "30" :state-name "Montana"},
   {:fips-code "31" :state-name "Nebraska"},
   {:fips-code "32" :state-name "Nevada"},
   {:fips-code "33" :state-name "New Hampshire"},
   {:fips-code "34" :state-name "New Jersey"},
   {:fips-code "35" :state-name "New Mexico"},
   {:fips-code "36" :state-name "New York"},
   {:fips-code "37" :state-name "North Carolina"},
   {:fips-code "38" :state-name "North Dakota"},
   {:fips-code "39" :state-name "Ohio"},
   {:fips-code "40" :state-name "Oklahoma"},
   {:fips-code "41" :state-name "Oregon"},
   {:fips-code "42" :state-name "Pennsylvania"},
   {:fips-code "44" :state-name "Rhode Island"},
   {:fips-code "45" :state-name "South Carolina"},
   {:fips-code "46" :state-name "South Dakota"},
   {:fips-code "47" :state-name "Tennessee"},
   {:fips-code "48" :state-name "Texas"},
   {:fips-code "49" :state-name "Utah"},
   {:fips-code "50" :state-name "Vermont"},
   {:fips-code "51" :state-name "Virginia"},
   {:fips-code "53" :state-name "Washington"},
   {:fips-code "54" :state-name "West Virginia"},
   {:fips-code "55" :state-name "Wisconsin"},
   {:fips-code "56" :state-name "Wyoming"}])

(def states-by-fips
  (into {} (map (fn [{:keys [fips-code state-name]}]
                  [fips-code state-name]) states)))
